package com.disney.composite.api.accommodationModule.soapServices.accommodationSalesComponentServicePort.processContainerModifyBusinessEvent;

public class TestProcessContainerModifyBusinessEvent_guarAccomm_nullTps {

}
