package com.disney.composite.api.accommodationModule.soapServices.accommodationSalesComponentServicePort.shareAccommodations;

public class Test_shareAccommodations_emptyRoomReservationDetail_Negative {

}
